repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        name: Enforce end of file format
        # Exclude generated static files
        exclude: '^wagtailsupertable/static/js/'

      - id: trailing-whitespace
        name: Enforce removal of trailing whitespace
        # Exclude generated static files
        exclude: '^wagtailsupertable/static/js/'

      - id: mixed-line-ending
        args: [--fix=lf]
        # Exclude generated static files
        exclude: '^wagtailsupertable/static/js/'

      - id: fix-byte-order-marker

      - id: check-json
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.9
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v17.16.0
    hooks:
      - id: stylelint
        files: \.css$
        additional_dependencies:
          - stylelint@17.16.0
          - stylelint-config-standard@40.0.0

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.39.1
    hooks:
      - id: eslint
        files: \.js$
        # Exclude generated static files
        exclude: '^wagtailsupertable/static/js/'
        additional_dependencies:
          - eslint@9.39.5
          - '@eslint/js@9.39.5'
          - eslint-plugin-import@2.32.0
          - globals@17.13.0

  - repo: https://github.com/JoC0de/pre-commit-prettier
    rev: v3.9.9
    hooks:
      - id: prettier
        files: \.js$
        # Exclude generated static files
        exclude: '^wagtailsupertable/static/js/'
