name: Auto approve

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - uses: hmarr/auto-approve-action@05a696a09d381a5a0d142c755f7eacbb19eb6525
